export { AddDoctorModal } from "./Doctor/AddDoctorModal"
export { DeleteDoctorConfirmation } from "./Doctor/DeleteDoctorConfirmation"
export { DoctorAvailabilityModal } from "./Doctor/UpdateDoctorAvailabilityModal"
export { UpdateDoctorDetailsModal } from "./Doctor/UpdateDoctorDetailsModal"
export { PatientCard } from "./Patient/PatientCard"
export { AddPatientModal } from "./Patient/AddPatientModal"
export { UpdatePatientModal } from "./Patient/UpdatePatientModal"
export { DeletePatientConfirmation } from "./Patient/DeletePatientConfirmation"