export { AdminLayout } from "./AdminLayout"
export { Doctor } from "./Doctor"
export { Doctor2 } from "./Doctor2"
export { Patient } from "./Patient"
export { Appointments } from "./Appointments"
export {Prescription} from "./Prescription"
export { Reports } from "./Reports" 
export { AppointmentHistory } from "./AppointmentHistory"
export { Analytics } from "./Analytics"