export { AdminLayout } from "./AdminLayout"
export {Doctor} from "./Doctor"
export { Patient } from "./Patient"
export { Appointments } from "./Appointments"
export {Prescription} from "./Prescription"
export { Reports } from "./Reports" 
export { AppointmentHistory } from "./AppointmentHistory"
export { Analytics } from "./Analytics"